### ISSUE TITLE
Smart Ref Unbinder are not always getting removed

### ISSUE THREAD

**Issue by saint11** [sigtrapgames/SmartData#6]
When the game crashes (for unrelated reasons) the Smart Ref Unbinder is not removed sometimes

![image](https://user-images.githubusercontent.com/4672703/47594286-f244b400-d950-11e8-9a9b-7d761c4d0ac5.png)

**Comment by SixWays** [comment]
Thanks for reporting! I've noticed this before but not worked out what causes it. I think I know now, but it turns out there's a deeper issue with the unbinding system (in editor that is). 

The unbinder is there to automatically remove the listener that fires the unityevent from the SmartRef when the object that owns it gets destroyed, so as not to leak the object (lapsed listener problem). Since the SmartRefs are plain classes they don't get OnDestroy etc, so SmartRefUnbinder is a surrogate to do it for them.

The problem is, the unbinder has to be created in OnAfterDeserialize as this (and OnBeforeSerialize) is the only callback I can make a plain class automatically receive - and what you can do during the deserialization phase of an object's lifecycle is extremely limited. So I'm unable to directly check Application.isPlaying for instance, which makes it hard to not create SmartRefUnbinders when playmode is stopped (which I believe is what's happenening).

I've got a way to get around that (check Application.isPlaying in SmartRefUnbinder.Start and destroy if so), but the larger problem is that when you press Play, the SmartRefUnbinder deserialisation seems to get called *before* Unity actually starts playing - so the SmartRefUnbinder gets auto-destroyed by the editor as it cleans up transient scene objects before playing. So I'm not sure this actually works properly at all!

**Comment by saint11** [comment]
As a band-aid solution I added a
```C#
private void Awake()
        {
            if (!Application.isPlaying)
            {
                DestroyImmediate(this);
            }
        }
```
and made it execute in edit mode 😄

**Comment by SixWays** [comment]
Ok, think it's fixed!

At the moment I serialize a ref to the owner MonoBehaviour to the SmartRef at edit time (in the PropertyDrawer for the SmartRef), and use that at deserialization time to add the SmartRefUnbinder to the same gameobject. I've managed to get this working properly in the above case (i.e. when you hit Play in the editor) and the way it *used* to work should still work in a build (and it defaults to that unless UNITY_EDITOR is defined).

I've also checked this still works with copying/instantiating something (since I wasn't sure if gameobject reference would get auto-changed by unity, but it seems to). So everything should be good. However I'll leave this open for now as I haven't tested in a build and there may be other unforeseen bugs.

I'm going to leave

**Comment by saint11** [comment]
It's removing the component but I don't think it's listening to changes to the variable anymore :(

**Comment by saint11** [comment]
Here's an example, am I doing something wrong?
[ProjectSettings.zip](https://github.com/sigtrapgames/SmartData/files/2522284/ProjectSettings.zip)

**Comment by sigtrapgames** [comment]
Issue solved. For the record saint11 and I have been working on fixing and testing it.
